name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels:
  - bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Include enough detail to reproduce it.
  - type: input
    id: version
    attributes:
      label: tuprwre version
      description: Run `tuprwre --version`
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear summary of the observed behavior and expected behavior.
      placeholder: Expected X, but saw Y.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include the exact commands and setup to reproduce.
      placeholder: |
        1. Command run:
        2. Environment:
        3. Output:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs or stderr output.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Sanity checks run
      options:
        - label: I can reproduce with `go test ./...`
        - label: I can reproduce with `go vet ./...`
        - label: I can reproduce with `go build ./cmd/tuprwre`
